# Generated by Django 2.2.5 on 2019-09-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=500)),
                ('CountryName', models.CharField(max_length=500)),
                ('StandNumber', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('Website', models.CharField(max_length=500)),
                ('ProductCatogery', models.CharField(max_length=500)),
                ('Year', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
                ('Phone', models.CharField(max_length=500)),
            ],
        ),
    ]
